name: polling

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests

      - name: run script
        run: python api.py

      - name: commit CSV to data branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout data || git checkout -b data
          git add output/output.csv
          git commit -m "Update output.csv" || echo "No changes to commit"
          git push origin data