name: polling

on:
  schedule:
    - cron: '*/15 * * * *'   # co 15 minut UTC
  workflow_dispatch:         # pozwala też ręczne uruchomienie

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests
          
      - name: Create output folder
        run: mkdir -p output

      # 5️⃣ Uruchomienie skryptu
      - name: Run polling script
        run: python api.py
        
      - name: Commit CSV to data branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git checkout data || git checkout -b data
          git add output/output.csv
          git commit -m "Update output.csv" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} data
